name: Release

on:
  workflow_dispatch:

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - name: Pack the project
        run: zip -r systemless-fcm-hosts.zip . -x "*.git*"
      - name: Generate release name with current date
        run: echo "RELEASE_NAME=$(date +'%Y%m%d')" >> $GITHUB_ENV
      - name: Delete the release if exists then create a new one
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh release view ${{ env.RELEASE_NAME }} && gh release delete ${{ env.RELEASE_NAME }} -y --cleanup-tag
          gh release create ${{ env.RELEASE_NAME }} --generate-notes Fcm-Hosts.zip
